version: '2'

services:
  xcatmn:
    image: xcat/xcat-ubuntu-x86_64 
    container_name: xcatmn
    hostname: xcatmn
    privileged: true
    extra_hosts: 
      - "xcatmn.clusers.com xcatmn:10.5.107.101"
    networks:
      default: 
        ipv4_address : 10.5.107.101
       
    volumes:
      - /docker/xcatdata/:/install

networks:
  default:
    external:
      name: subnet1
